### ISSUE TITLE
Investigate and Resolve differences between DRAGEN/GVS and GATK/WARP seqr callsets

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/tgg_methods#82]
The new seqr callsets are going to be using DRAGEN and GVS to create the delivered VCFs. We need to identify all differences between the two callsets and make any needed changes to the seqr loading pipeline.

Document describing DRAGEN, GVS, and some known differences from our previous callsets is [here](https://docs.google.com/document/d/18GqYqsN01k7YX6wRecA8umCLx28NrRP21g6UsVGDIDA/edit).

**Comment by matren395** [comment]
Updating my tickets now, trying to get a bit more organized. 

This was resolved! Data from the WGS DRAGEN callset was loaded in May 2024. Key differences included: HET GQ differences, Ploidy of Sex Chromosomes, and different rare variant calling behavior
