### ISSUE TITLE
Run s&r checks on the 2 projects with the new pipeline

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/tgg_methods#94]

**Comment by jialanm** [comment]
Got results back at: 
`gs://seqr-hail-search-data/v03/GRCh38/SNV_INDEL/runs/manual__2024-05-06T15-23-29+00-00/metadata.json`
Can be viewed by: 
`gsutil cat gs://seqr-hail-search-data/v03/GRCh38/SNV_INDEL/runs/manual__2024-05-06T15-23-29+00-00/metadata.json | jq '.failed_family_samples'`
